import React from "react";
import "./globals.css"
import Header from './components/header'
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function DashboardLayout({children,}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body >
    <Header/>
    {children}
    </body>
    </html>
  );
}
